<?php

namespace App\Services;

use App\Models\MikrotikConnection;
use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use RuntimeException;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

class RadiusClientsSynchronizer
{
    public function __construct(private Filesystem $filesystem) {}

    /**
     * @throws FileNotFoundException
     * @throws ProcessFailedException
     */
    public function sync(): void
    {
        $connections = MikrotikConnection::query()
            ->where('is_active', true)
            ->whereNotNull('radius_secret')
            ->with('wgPeer')
            ->get();

        $payload = $this->buildClientsPayload($connections);
        $path = (string) config('radius.clients_path');
        $directory = dirname($path);

        // Try direct write first
        $canWrite = $this->filesystem->isDirectory($directory)
            && $this->filesystem->isWritable($directory)
            && (! $this->filesystem->exists($path) || $this->filesystem->isWritable($path));

        if ($canWrite) {
            $this->filesystem->put($path, $payload);
            $this->reloadRadius();
            return;
        }

        // Fallback: use sudo wrapper script (requires /etc/sudoers.d/rafen-freeradius entry)
        $process = Process::fromShellCommandline('sudo /usr/local/bin/rafen-sync-radius-clients');
        $process->run();

        if (! $process->isSuccessful()) {
            throw new RuntimeException(
                "Tidak dapat menulis ke {$directory} dan fallback sudo juga gagal: " . $process->getErrorOutput()
            );
        }
    }

    /**
     * Write payload to file and reload FreeRADIUS (called directly when writable).
     */
    public function writeAndReload(string $payload): void
    {
        $path = (string) config('radius.clients_path');
        $this->filesystem->put($path, $payload);
        $this->reloadRadius();
    }

    public function buildPayload(): string
    {
        $connections = MikrotikConnection::query()
            ->where('is_active', true)
            ->whereNotNull('radius_secret')
            ->with('wgPeer')
            ->get();

        return $this->buildClientsPayload($connections);
    }

    private function reloadRadius(): void
    {
        $command = (string) config('radius.reload_command');
        if ($command === '') {
            return;
        }

        $process = Process::fromShellCommandline($command);
        $process->run();

        if (! $process->isSuccessful()) {
            throw new ProcessFailedException($process);
        }
    }

    private function buildClientsPayload(Collection $connections): string
    {
        $lines = [
            '# Generated by Laravel - do not edit manually',
        ];

        foreach ($connections as $connection) {
            $shortName = Str::slug($connection->name, '_') ?: 'mikrotik_'.$connection->id;
            $secret = addslashes($connection->radius_secret);

            $wgPeer = $connection->wgPeer;
            $viaWg  = $wgPeer?->is_active && $wgPeer->vpn_ip;
            $nasIp  = $viaWg ? $wgPeer->vpn_ip : $connection->host;
            $nasNote = $viaWg ? '# NAS IP via WireGuard tunnel' : '# NAS IP: direct (public)';
            $requireMsgAuth = $viaWg ? 'yes' : 'no';

            $lines[] = $nasNote;
            $lines[] = "client {$shortName} {";
            $lines[] = "    ipaddr = {$nasIp}";
            $lines[] = "    secret = {$secret}";
            $lines[] = "    shortname = {$shortName}";
            $lines[] = "    require_message_authenticator = {$requireMsgAuth}";
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }
}
