<?php

return [
    // Public host/IP of the WireGuard server (for MikroTik script generation)
    'host' => env('WG_HOST', ''),

    // Server IP on the tunnel interface (e.g. 10.0.0.1) — used in RADIUS script
    'server_ip' => env('WG_SERVER_IP', '10.0.0.1'),

    // Server address including prefix (e.g. 10.0.0.1/24) — written to wg0.conf [Interface]
    'server_address' => env('WG_SERVER_ADDRESS', '10.0.0.1/24'),

    // Server private key (generated by install-wg.sh, stored in /etc/wireguard/server_private.key)
    'server_private_key' => env('WG_SERVER_PRIVATE_KEY', ''),

    // Server public key (displayed in UI and embedded in MikroTik scripts)
    'server_public_key' => env('WG_SERVER_PUBLIC_KEY', ''),

    // UDP port WireGuard listens on
    'listen_port' => env('WG_LISTEN_PORT', '51820'),

    // WireGuard interface name
    'interface' => env('WG_INTERFACE', 'wg0'),

    // Absolute path to wg0.conf
    'config_path' => env('WG_CONFIG_PATH', '/etc/wireguard/wg0.conf'),

    // IP pool for auto-allocation to peers (server uses .1, peers start at .2)
    'pool_start' => env('WG_POOL_START', '10.0.0.2'),
    'pool_end'   => env('WG_POOL_END',   '10.0.0.254'),

    // PostUp / PostDown NAT rules (empty = not written to wg0.conf)
    'post_up'   => env('WG_POST_UP',   ''),
    'post_down' => env('WG_POST_DOWN', ''),
];
